const Cdata = [{
  id: 1,
  title: "Best Tricks",
  heading: "Slick slider",
  description: "in this blog you find how to use slick slider in  reactjs",
  link: "https://github.com/akiran/react-slick",
  docs: "documentation",
  imgsrc: "./images/silk.png",
  sub: "HTML5 CSS3 js",
  link1: "https://kenwheeler.github.io/slick/"
},
  {
    id: 2,
    heading: "particles.js",
    description: "in this blog you find how to use particles in  reactjs",
    link: "https://github.com/Wufe/react-particles-js",
    docs: "documentation",
    imgsrc: "./images/partical.jpeg",
    sub: "HTML5 CSS3 js",
    link1: "https://vincentgarreau.com/particles.js/"
  },
  {
    id: 3,
    heading: "typewriter effect",
    description: "in this blog you find how to use typing effect in  reactjs",
    docs: "documentation",
    link: "https://www.npmjs.com/package/typewriter-effect",
    imgsrc: "./images/typing.gif",
    sub: "HTML5 CSS3 js",
    link1: "https://github.com/mattboldt/typed.js/"
  },
  {
    id: 4,
    heading: "Vanilla-tilt.js",
    description: "in this blog you find how to use Vanilla-tilt effect in  reactjs",
    docs: "documentation",
    link: "https://micku7zu.github.io/vanilla-tilt.js/",
    imgsrc: "./images/vanilla.jpeg",
    sub: "HTML5 CSS3 js",
    link1: "https://micku7zu.github.io/vanilla-tilt.js/"
  },
  {
    id: 5,
    heading: "flatuicolors",
    description: "in this blog you find copy hex code of colours",
    link: "https://flatuicolors.com/",
    imgsrc: "./images/color.gif",
  },
  {
    id: 6,
    heading: "getwaves",
    description: "in this blog you will add awesome waves in your website",
    link: "https://getwaves.io/",
    imgsrc: "./images/waves.png",
  },
  {
    id: 7,
    heading: "bennettfeely",
    description: "in this blog you will add awesome clip path in your website",
    link: "https://bennettfeely.com/clippy/",
    imgsrc: "./images/clip.jpeg",
  },
  {
    id: 8,
    heading: "toolpit",
    description: "in this blog you will add awesome toolpit in your website",
    link: "https://popper.js.org/",
    imgsrc: "./images/popper.jpeg",
  },
  {
    id: 9,
    heading: "boxicons",
    description: "in this blog you will add awesome icons in your website",
    link: "https://boxicons.com/",
    imgsrc: "./images/icon.jpeg",
  },
  {
    id: 10,
    heading: "react-toastify",
    description: "in this blog you will add toastify in your website",
    link: "https://fkhadra.github.io/react-toastify/introduction/",
    imgsrc: "./images/toast.jpeg",
  },
  {
    id: 11,
    heading: "material-ui icon",
    description: "in this blog you will add material-ui icons in your reactjs website",
    link: "https://material-ui.com/getting-started/installation/",
    imgsrc: "./images/material.jpeg",
  },
  {
    id: 12,
    heading: "Bootstrap",
    docs: "documentation",
    description: 'in this blog you will add Bootstrap in your reactjs website',
    link1: "https://getbootstrap.com/",
    link: "https://stackoverflow.com/questions/40037657/how-to-include-bootstrap-css-and-js-in-reactjs-app",
    imgsrc: "./images/bootstrap.jpeg",
    sub: "HTML5 CSS3 js",
  },
    {
    id: 13,
    heading: "",
    docs: "documentation",
    description: 'in this blog you will own create cheatsheet in  website',
    link1: "https://prismjs.com/",
    link: "https://medium.com/get-it-working/get-prismjs-working-in-react-a6d989e59290#:~:text=import%20React%20from%20%22react%22%3B,and%20foot%20of%20the%20page).",
    imgsrc: "./images/prism.jpeg",
    sub: "HTML5 CSS3 js",
  },
]
export default Cdata;